name: 🐞 Bug Report
description: Report something that is broken or not working as expected
title: "[Bug]: "
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the issue you encountered.
      placeholder: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: What steps did you take to trigger this bug?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: It should have...

  - type: textarea
    id: env
    attributes:
      label: Environment Info
      description: Provide environment details.
      placeholder: |
        - OS: [e.g., Windows 11, macOS 13]
        - Browser: [e.g., Chrome 114]
        - Extension/App Version: [e.g., v1.2.0]

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add screenshots, logs, or other helpful context.
